### ISSUE TITLE
Sims 4 + Deluxe in library causes Galaxy to count 2 installed games

### ISSUE THREAD

**Issue by fl4shback** [FriendsOfGalaxy/galaxy-integration-origin#28] opened 2021-01-12 18:51 UTC
Hi!

I own both TS4 and TS4 Deluxe in Origin (releases OFB-EAST:109552299 and OFB-EAST:109552414) they show up correctly in Galaxy
But the plugin seems to report them as 2 different games causing Galaxy add 2 installed games but only one "real game" in the library.

[plugin-origin-7f53219b-4e2b-4591-9f4f-dfc5f4ba9eb0.log](https://github.com/FriendsOfGalaxy/galaxy-integration-origin/files/5804158/plugin-origin-7f53219b-4e2b-4591-9f4f-dfc5f4ba9eb0.log)

**Comment by FriendsOfGalaxy** [comment] 2021-01-19 13:09
Hi @fl4shback 

In this plugin we operate at Origin offers - so yes - those will be reported as separate game releases - as designed.

How it looks in Galaxy library? Are those releases stacked under one game tile?

Could you attach content of your C:\ProgramData\Origin\LocalContent ?

**Comment by fl4shback** [comment] 2021-01-19 20:00
Hi @FriendsOfGalaxy 

I only have TS4 installed on Origin. Here's my LocalContent folder.
[LocalContent.zip](https://github.com/FriendsOfGalaxy/galaxy-integration-origin/files/5838282/LocalContent.zip)

As you can see on those screenshots, logging out of Origin plugin removes 2 installed games from my gog library.

**Logged in**
![cap1](https://user-images.githubusercontent.com/57314569/105085793-89e5ce00-5a98-11eb-855a-594b6c9dd093.png)
**Logged out**
![cap2](https://user-images.githubusercontent.com/57314569/105085796-8b16fb00-5a98-11eb-91c7-a1f6dd9e9afb.png)

On the product page, both versions are grouped together but I can see that both are displayed as "local"
![cap3](https://user-images.githubusercontent.com/57314569/105086378-388a0e80-5a99-11eb-82e9-ed791b52fdcd.png)
![cap4](https://user-images.githubusercontent.com/57314569/105086380-3922a500-5a99-11eb-8b0e-01da04e9cf76.png)

**Comment by FriendsOfGalaxy** [comment] 2021-01-22 16:31
Plugin logic is simple - return every offer as separate game, Galaxy will group those offers under one tile if needed. 

Local (installed) games are returned just based on LocalContent directory - so plugin reports 72 installed "games" in your case (those are probably different sims DLCs? Galaxy does not support DLCs yet) based on .mfst files from LocalContent directory.

Galaxy shows only those installed games that have corresponding "owned" game - so 2 in your case.

I'm not convinced to do any change here like  trying to deduplicate or filter out owned games before we send it to Galaxy. That sounds risky - it is more safe to return everything than trying to judge which offer is "better", or assuming that all local games are launchable by one and the same exe. 

If you or anyone have some time to research origin internals on multiple examples - you're welcome. Having strong evidence what should be filtered out based on some kind of simple logic - I'll be happy to made code review.

Tip: you can check `masterTitleId` in origin API that is used to gather owned_games.

**Comment by FriendsOfGalaxy** [comment] 2021-01-22 16:33
Or wait - is it possible to "install" both sims versions simulanously on Origin? Then there will be mistake in reading local games in the plugin

**Comment by fl4shback** [comment] 2021-01-22 16:39
Yeah, I see where you are coming from, seems risky.

Games are listed as 2 separate releases on Origin. Both are listed as installed... Seems like their way of doing it is what's causing the duplication in Galaxy.

(screenshot incoming)

**Comment by FriendsOfGalaxy** [comment] 2021-01-22 19:58
yeah, looks like Origin issue - we usually don't want to fix their issues but implementing hacks - its too risky. If they fix it somehow, then it is a good chance that it will be fixed in Galaxy as well.

**Comment by FriendsOfGalaxy** [comment] 2021-01-22 19:59
Let me know about what they say, but for now - I'm closing the issue. Anyway - thanks for your time to care and report it

**Closed by FriendsOfGalaxy** 2021-01-22 19:59 UTC
Labels: wontfix
