### ISSUE TITLE
Origin plugin crashing due to: ModuleNotFoundError: No module named 'aiohttp.http_writer'

### ISSUE THREAD

**Issue by gigabit942007** [FriendsOfGalaxy/galaxy-integration-origin#21] opened 2020-06-19 16:44 UTC
**Describe the bug**
Origin plugin is crashing on GOG Galaxy startup due to missing 'aiohttp.http_writer'.

**Expected behavior**
Origin plugin should not crash. Upon disconnecting Origin you cannot add them anymore due to the plugin crashing.

**Attached logs**
[plugin-origin-7f53219b-4e2b-4591-9f4f-dfc5f4ba9eb0.log](https://github.com/FriendsOfGalaxy/galaxy-integration-origin/files/4805796/plugin-origin-7f53219b-4e2b-4591-9f4f-dfc5f4ba9eb0.log)

**Comment by FriendsOfGalaxy** [comment] 2020-06-29 11:53
Strange. Looks like not donwloaded properly by Galaxy or somethinig (antivirus?) has removed some plugin files. What if you install it manually?

- Go to https://github.com/FriendsOfGalaxy/galaxy-integration-origin/releases and download `<your_os>.zip`
- Close Galaxy
- remove origin plugin (whole folder) from `%LocalAppData%\GOG.com\Galaxy\plugins\installed`
- extract downloaded zip to `%LocalAppData%\GOG.com\Galaxy\plugins\installed`
- Open Galaxy

**Comment by gigabit942007** [comment] 2020-06-30 16:32
I have just done the steps above and now the integration works correctly, it does not crash anymore.

I'm running Windows 10 version 1909 with just Windows Defender. I checked to see maybe some files were marked as viruses but they were not marked, the log is clean.

For good measure i've reinstalled GOG a couple of times and cleaned all folders just to be sure, but the bug was still there (this was when i reported the bug initially), i was using version V0.35 at that time, i see that 0.36 is available, with manual installation it works correctly.

**Comment by FriendsOfGalaxy** [comment] 2020-07-01 14:49
Hmm, strange. I wonder if the bug could be ditched if you remove `%LocalAppData%\GOG.com\Galaxy\plugins\installed` and `%LocalAppData%\GOG.com\Galaxy\plugins\downloaded` (reinstallation of Galaxy will not help, plugins are put in localappdata).

If you want, you can help Galaxy team to with this issue by
- trying to reproduce it by disconnecting current origin plugin, removing it from `%LocalAppData%\GOG.com\Galaxy\plugins\installed`, restarting and then Connecting again.
- report to their bug-tracker via Galaxy - `Report Issue` attaching your log files from `%programdata%\GOG.com\Galaxy\logs`

My guess is some files were missed while downloading... do they verify download sha or size? 

I'm closing as I cannot help on plugin side. Anyway, thanks for checking if manual installation works

**Closed by FriendsOfGalaxy** 2020-07-01 14:49 UTC
